-- Appointment status timeline for the 0.3.2 clinic flow board.
-- Times are generated by Postgres and stored as timestamptz. The desktop app
-- displays them in Asia/Manila without trusting a workstation clock for writes.

create table public.appointment_status_events (
  id uuid primary key default gen_random_uuid(),
  appointment_id uuid not null
    references public.appointments(id) on delete restrict,
  previous_status text,
  next_status text not null,
  recorded_at timestamptz not null default now(),
  recorded_by uuid references public.profiles(id) on delete set null,
  event_source text not null default 'status_change',
  constraint appointment_status_events_previous_status_check check (
    previous_status is null
    or previous_status in (
      'scheduled',
      'confirmed',
      'arrived',
      'intake_in_progress',
      'in_session',
      'completed',
      'cancelled',
      'no_show'
    )
  ),
  constraint appointment_status_events_next_status_check check (
    next_status in (
      'scheduled',
      'confirmed',
      'arrived',
      'intake_in_progress',
      'in_session',
      'completed',
      'cancelled',
      'no_show'
    )
  ),
  constraint appointment_status_events_source_check check (
    event_source in ('appointment_created', 'status_change', 'migration_snapshot')
  )
);

comment on table public.appointment_status_events is
  'Immutable server-timed appointment workflow milestones.';
comment on column public.appointment_status_events.recorded_at is
  'Authoritative database time; display in Asia/Manila in the clinic app.';

create index appointment_status_events_appointment_recorded_idx
  on public.appointment_status_events (appointment_id, recorded_at desc);
create index appointment_status_events_recorded_by_idx
  on public.appointment_status_events (recorded_by)
  where recorded_by is not null;
create index appointment_status_events_next_recorded_idx
  on public.appointment_status_events (next_status, recorded_at desc);

create or replace function public.hpc_record_appointment_status_event()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
begin
  -- Backup restore uses the service role and restores the original event rows.
  if coalesce(auth.jwt() ->> 'role', '') = 'service_role' then
    return new;
  end if;

  if tg_op = 'UPDATE' and new.status is not distinct from old.status then
    return new;
  end if;

  insert into public.appointment_status_events (
    appointment_id,
    previous_status,
    next_status,
    recorded_at,
    recorded_by,
    event_source
  ) values (
    new.id,
    case when tg_op = 'INSERT' then null else old.status end,
    new.status,
    now(),
    auth.uid(),
    case when tg_op = 'INSERT' then 'appointment_created' else 'status_change' end
  );

  return new;
end;
$function$;

drop trigger if exists appointments_status_timeline on public.appointments;
create trigger appointments_status_timeline
  after insert or update of status on public.appointments
  for each row execute function public.hpc_record_appointment_status_event();

-- Earlier staging appointments cannot be assigned invented milestone times.
-- Capture only their current state and label it clearly as an upgrade snapshot.
insert into public.appointment_status_events (
  appointment_id,
  previous_status,
  next_status,
  recorded_at,
  recorded_by,
  event_source
)
select
  appointment.id,
  null,
  appointment.status,
  now(),
  null,
  'migration_snapshot'
from public.appointments as appointment
where not exists (
  select 1
  from public.appointment_status_events as status_event
  where status_event.appointment_id = appointment.id
);

alter table public.appointment_status_events enable row level security;

revoke all on table public.appointment_status_events
  from public, anon, authenticated;
grant select on table public.appointment_status_events to authenticated;

create policy "appointment status events select by calendar role"
  on public.appointment_status_events for select to authenticated
  using (
    public.hpc_current_profile_has_role(array['admin', 'staff'])
    or exists (
      select 1
      from public.appointments appointment
      join public.profiles profile
        on profile.id = (select auth.uid())
      where appointment.id = appointment_status_events.appointment_id
        and appointment.provider_profile_id = (select auth.uid())
        and profile.is_active = true
        and nullif(
          btrim(coalesce(profile.hpc_representative_name, '')),
          ''
        ) is not null
    )
  );

create policy "appointment status events require mfa"
  on public.appointment_status_events as restrictive for select to authenticated
  using (public.hpc_has_required_aal());

revoke execute on function public.hpc_record_appointment_status_event()
  from public, anon, authenticated;

-- Include the timeline in the existing merge-only clinic backup restore.
create or replace function public.hpc_restore_backup_service(
  p_backup jsonb,
  p_actor_user_id uuid
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $function$
declare
  table_item record;
  table_rows jsonb;
  column_list text;
  update_list text;
  statement_text text;
  affected_count integer;
  restored_counts jsonb := '{}'::jsonb;
  backup_format integer;
begin
  if coalesce(auth.jwt() ->> 'role', '') <> 'service_role'
     and current_role <> 'service_role' then
    raise exception 'Restore service is not available to this session.';
  end if;

  if p_backup is null or jsonb_typeof(p_backup) <> 'object' then
    raise exception 'The restore package is not a JSON object.';
  end if;

  backup_format := coalesce((p_backup ->> 'format_version')::integer, 0);
  if backup_format <> 2 then
    raise exception 'Unsupported backup format version.';
  end if;

  if jsonb_typeof(p_backup -> 'tables') <> 'object' then
    raise exception 'The restore package does not contain a tables object.';
  end if;

  -- Merge-only restore. Records absent from the package are never deleted.
  -- Profiles remain excluded because Auth identities are managed by Supabase Auth.
  for table_item in
    select *
    from (values
      (1, 'client_categories'::text, 'id'::text),
      (2, 'clinic_settings'::text, 'id'::text),
      (3, 'appointment_services'::text, 'id'::text),
      (4, 'clinic_hours'::text, 'weekday'::text),
      (5, 'clients'::text, 'id'::text),
      (6, 'care_team_availability'::text, 'id'::text),
      (7, 'care_team_availability_overrides'::text, 'id'::text),
      (8, 'appointments'::text, 'id'::text),
      (9, 'appointment_status_events'::text, 'id'::text),
      (10, 'client_children'::text, 'id'::text),
      (11, 'client_4ps'::text, 'id'::text),
      (12, 'client_cssrs'::text, 'client_id'::text),
      (13, 'progress_notes'::text, 'id'::text),
      (14, 'client_documents'::text, 'id'::text),
      (15, 'client_assessments'::text, 'id'::text),
      (16, 'dashboard_announcements'::text, 'id'::text)
    ) as restore_tables(sort_order, table_name, conflict_column)
    order by sort_order
  loop
    table_rows := coalesce(p_backup -> 'tables' -> table_item.table_name, '[]'::jsonb);

    if jsonb_typeof(table_rows) <> 'array' then
      raise exception 'Backup table % must be an array.', table_item.table_name;
    end if;

    if jsonb_array_length(table_rows) = 0 then
      restored_counts := restored_counts || jsonb_build_object(table_item.table_name, 0);
      continue;
    end if;

    select
      string_agg(format('%I', attribute.attname), ', ' order by attribute.attnum),
      string_agg(
        format('%I = excluded.%I', attribute.attname, attribute.attname),
        ', ' order by attribute.attnum
      ) filter (where attribute.attname <> table_item.conflict_column)
    into column_list, update_list
    from pg_attribute as attribute
    where attribute.attrelid = format('public.%I', table_item.table_name)::regclass
      and attribute.attnum > 0
      and not attribute.attisdropped
      and attribute.attgenerated = '';

    statement_text := format(
      'insert into public.%I (%s) '
      || 'select %s from jsonb_populate_recordset(null::public.%I, $1) '
      || 'on conflict (%I) do update set %s',
      table_item.table_name,
      column_list,
      column_list,
      table_item.table_name,
      table_item.conflict_column,
      update_list
    );

    execute statement_text using table_rows;
    get diagnostics affected_count = row_count;
    restored_counts := restored_counts || jsonb_build_object(table_item.table_name, affected_count);
  end loop;

  insert into public.audit_logs (
    actor_user_id,
    module,
    action,
    target_type,
    target_label,
    details
  ) values (
    p_actor_user_id,
    'Settings',
    'Restored Clinic Backup',
    'backup',
    coalesce(p_backup ->> 'export_id', p_backup ->> 'exported_at', 'Clinic backup'),
    jsonb_build_object(
      'restore_mode', 'merge',
      'format_version', backup_format,
      'source_project_ref', p_backup ->> 'source_project_ref',
      'restored_counts', restored_counts,
      'profiles_restored', false,
      'storage_files_restored', false
    )
  );

  return jsonb_build_object(
    'ok', true,
    'mode', 'merge',
    'restored_counts', restored_counts,
    'profiles_restored', false,
    'storage_files_restored', false
  );
end;
$function$;

revoke all on function public.hpc_restore_backup_service(jsonb, uuid)
  from public, anon, authenticated;
grant execute on function public.hpc_restore_backup_service(jsonb, uuid)
  to service_role;
